-- CREATE DATABASE wishlists;

DROP TABLE IF EXISTS listitems;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS lists;
DROP TABLE IF EXISTS people;

CREATE TABLE people(
    pID SERIAL PRIMARY KEY,
    pFirstName VARCHAR(50) NOT NULL
);

CREATE TABLE lists( 
    lID SERIAL PRIMARY KEY,
    pID INT REFERENCES people NOT NULL,
    lname VARCHAR(50) NOT NULL
);

CREATE TABLE items(
    iID SERIAL PRIMARY KEY,
    iName VARCHAR(50) NOT NULL
);

create table listItems(
    liID SERIAL PRIMARY KEY,
    lID int REFERENCES lists NOT NULL,
    iID INT REFERENCES items NOT NULL,
    liDesired INT NOT NULL DEFAULT 1,
    liPurchased INT NOT NULL DEFAULT 0
);

ALTER TABLE people 
ADD COLUMN plastName VARCHAR(50) NOT NULL,
ADD COLUMN pcity VARCHAR(50) NOT NULL,
ADD COLUMN pstate VARCHAR(2) NOT NULL;